# Generated by Django 4.2.13 on 2024-07-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workstream', '0002_alter_workstream_owner'),
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='workstream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_invite', to='workstream.workstream'),
        ),
    ]
