# Generated by Django 4.2.13 on 2024-07-17 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invite', '0002_alter_invite_workstream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invite', to=settings.AUTH_USER_MODEL),
        ),
    ]
