# Generated by Django 4.2.13 on 2024-07-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0003_alter_invite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
