# Generated by Django 3.2.4 on 2024-06-10 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workstream', '0002_alter_workstream_owner'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_workstream',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workstream.workstream'),
        ),
    ]
