# Generated by Django 3.2.4 on 2024-06-13 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workstream', '0002_alter_workstream_owner'),
        ('profiles', '0002_profile_default_workstream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_workstream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workstream.workstream'),
        ),
    ]
